<?php
/**
 * Storage Panel — Configuration
 *
 * This file is regenerated by install.sh. You can edit it manually,
 * but be careful with STORAGE_ROOT — it defines the security boundary
 * for every file operation in the panel.
 */

// ---------------------------------------------------------------------
// STORAGE ROOT
// ---------------------------------------------------------------------
// Absolute path to the directory the panel is allowed to manage.
// EVERY file operation is confined inside this directory. Never point
// this at /, /etc, /root, /proc, /sys, /var/lib, /boot, or any other
// system path.
if (!defined('STORAGE_ROOT')) {
    define('STORAGE_ROOT', getenv('STORAGE_ROOT') ?: '/var/www/storage');
}

// ---------------------------------------------------------------------
// PANEL PATHS
// ---------------------------------------------------------------------
define('PANEL_ROOT', __DIR__);
define('DB_PATH', PANEL_ROOT . '/database/panel.sqlite');
define('LOG_PATH', PANEL_ROOT . '/logs/app.log');
define('TMP_UPLOAD_DIR', sys_get_temp_dir() . '/storage-panel-uploads');

// ---------------------------------------------------------------------
// SECURITY
// ---------------------------------------------------------------------
define('SESSION_NAME', 'sp_session');
define('SESSION_TIMEOUT_SECONDS', 30 * 60);      // 30 minutes idle timeout
define('LOGIN_MAX_ATTEMPTS', 5);
define('LOGIN_LOCKOUT_SECONDS', 15 * 60);        // 15 minutes lockout
define('CSRF_TOKEN_NAME', 'csrf_token');

// Cookie security. FORCE_SECURE_COOKIE=true requires HTTPS — set this
// to true once you have TLS configured (strongly recommended).
define('FORCE_SECURE_COOKIE', false);

// ---------------------------------------------------------------------
// UPLOAD / FILESYSTEM LIMITS
// ---------------------------------------------------------------------
define('CHUNK_SIZE_BYTES', 5 * 1024 * 1024);     // 5MB chunks for large uploads
define('DEFAULT_ALLOWED_EXTENSIONS', '*');        // '*' = all allowed (still filtered by BLOCKED)
define('DEFAULT_BLOCKED_EXTENSIONS', 'php,php3,php4,php5,phtml,phar,exe,sh,cgi,pl');

// Editable text-like extensions (used to gate the code editor)
define('EDITABLE_EXTENSIONS', [
    'txt','php','html','htm','css','js','json','xml','yaml','yml',
    'md','log','conf','env','ini','sql','sh','py','csv','htaccess'
]);

// Previewable extensions by category
define('PREVIEW_IMAGE_EXT', ['jpg','jpeg','png','gif','webp','svg']);
define('PREVIEW_VIDEO_EXT', ['mp4','webm','mov']);
define('PREVIEW_AUDIO_EXT', ['mp3','wav','ogg']);
define('PREVIEW_TEXT_EXT',  ['txt','json','html','htm','css','js','php','md','conf','env','log','xml','yaml','yml']);
define('PREVIEW_PDF_EXT',   ['pdf']);

// ---------------------------------------------------------------------
// TIMEZONE
// ---------------------------------------------------------------------
date_default_timezone_set(getenv('PANEL_TIMEZONE') ?: 'UTC');

// ---------------------------------------------------------------------
// ERROR HANDLING — never leak internals to the browser
// ---------------------------------------------------------------------
ini_set('display_errors', '0');
ini_set('log_errors', '1');
ini_set('error_log', LOG_PATH);
error_reporting(E_ALL);

// Ensure runtime directories exist
foreach ([dirname(DB_PATH), dirname(LOG_PATH), TMP_UPLOAD_DIR, STORAGE_ROOT] as $dir) {
    if (!is_dir($dir)) {
        @mkdir($dir, 0750, true);
    }
}
